AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  harmon-portfolio-backend

  SAM Template for harmon-portfolio-backend

Globals:
  Api:
    Cors:
      AllowMethods: "'GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  VisitorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VisitorCounter
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  VisitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: VisitorCounterFunction
      Role: arn:aws:iam::475029595046:role/harmon-portfolio-basic-lambda-role
      Runtime: python3.13
      Handler: app.lambda_handler
      CodeUri: visitor_counter/
      MemorySize: 128
      Timeout: 5
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorTable
      Environment:
        Variables:
          TABLE_NAME: !Ref VisitorTable
      Events:
        VisitorApi:
          Type: Api
          Properties:
            Path: /count
            Method: GET

Outputs:
  VisitorApiUrl:
    Description: API Gateway endpoint URL for visitor counter
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/count"
